version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - 8001:8001
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - ALLOWED_HOSTS=127.0.0.1, localhost, 0.0.0.0
      - DEBUG=True
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
